version: '3'

services:
  app:
    build: .
    entrypoint: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000

  db:
    image: keinos/sqlite3:latest
    restart: always
    tty: true
    volumes:
      -   ./.docker/dbdata:/data/db
    ports:
      - 9000:9000